name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    # ----------------------------
    # 1️⃣ Checkout
    # ----------------------------
    - name: Checkout code
      uses: actions/checkout@v4

    # ----------------------------
    # 2️⃣ Python setup + tests
    # ----------------------------
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest tests/

    # ----------------------------
    # 3️⃣ Configure AWS credentials
    # ----------------------------
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # ----------------------------
    # 4️⃣ Upload model/artifacts to S3
    # ----------------------------
    - name: Upload model to S3
      run: |
        aws s3 sync models/ s3://${{ secrets.S3_BUCKET_NAME }}/models/ --delete

    # ----------------------------
    # 5️⃣ Login to Amazon ECR
    # ----------------------------
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    # ----------------------------
    # 6️⃣ Build & Push Docker Image to ECR
    # ----------------------------
    - name: Build and Push Docker Image
      run: |
        IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
        SHA_IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${{ github.sha }}

        docker build -t $IMAGE_URI -t $SHA_IMAGE .
        docker push $IMAGE_URI
        docker push $SHA_IMAGE
